FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y sudo
RUN apt-get clean

RUN curl -fsSL https://code-server.dev/install.sh | sh

EXPOSE 8080

CMD ["code-server", "--bind-addr", "0.0.0.0:8080", "--auth", "password"]

 