FROM ubuntu:latest

RUN apt-get update && apt-get install -y curl

RUN curl -fsSc https://code-server.dev/install.hs | sh

EXPOSE 8080

CMD ["code-server", "--bind-addr", "0.0.0.0:8080", "--auth", "password", "/home/codes/project"]
 